global:
  scrape_interval:     10s
  evaluation_interval: 10s

  external_labels:
      monitor: 'backend'

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'


scrape_configs:

  - job_name: 'redfish-exporter'
    scrape_interval: 5s
    metrics_path: /redfish
    static_configs:
      - targets: [ '192.168.64.1:9141' ]

  - job_name: 'vsphere-exporter'
    scrape_interval: 5s
    metrics_path: /vsphere
    static_configs:
      - targets: [ '192.168.64.1:9142' ]

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
         - targets: ['host.docker.internal:9090'] # Only works on Docker Desktop for Mac
        # - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    scrape_interval: 5s
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100
