{
 "title": "Redfish",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "query": { "query": "label_values(host)" } }
  ]
 },
 "panels": [
  {
   "title": "Sensor temperature",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redfish_exporter_SensorTemperature{host=~\"$host\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Sensor health",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 3, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redfish_exporter_SensorHealth{host=~\"$host\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Power consumption",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 8, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "redfish_exporter_PowerConsumedWatts{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Redfish services",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redfish_exporter_up{} == 1 ", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Fan temperature",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redfish_exporter_FanTemperature{host=~\"$host\"}",
     "legendFormat": "{{fan}}"
    }
   ]
  },
  {
   "title": "Fan health",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redfish_exporter_FanStatus{host=~\"$host\"}",
     "legendFormat": "{{fan}}"
    }
   ]
  }
 ]
}