{
 "title": "vSphere",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "query": { "query": "label_values(host)" } }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "vsphere_exporter_UsageCPU{host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "vsphere_exporter_UsageRAM{host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hardware info",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "vsphere_exporter_HardwareInfo{host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sensor info",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "vsphere_exporter_SensorInfo{host=~\"$host\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Uptime in minutes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vsphere_exporter_RunTime{host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vSphere exporter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vsphere_exporter_up{} == 1 ", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Overall health",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "vsphere_exporter_OverallStatus{host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}